module.exports = {
  types: {
    sexualOrientation: [
      "Bisexual",
      "Gay",
      "Heterosexual",
      "Lesbian",
      "Queer",
      "Questioning",
      "Other/not listed",
      "I'd prefer not to say",
    ],
    ethnicity: [
      "White British",
      "White Gypsy/Irish Traveller",
      "White Irish",
      "White/White European",
      "Other White background",
      "Hispanic or Latinx",
      "Asian Bangladeshi",
      "Asian British",
      "Asian Chinese",
      "Asian Indian",
      "Asian Pakistani",
      "Other Asian background",
      "Black African",
      "Black Caribbean",
      "African American",
      "Other Black background",
      "Mix/Multiple ethnic background",
      "Middle Eastern/Arab",
      "I'd prefer not to say",
    ],
    parentsWorkInPress: [
      "Mom",
      "Dad",
      "Both",
      "Neither",
      "I'd prefer not to say",
    ],
    gender: [
      "Female",
      "Male",
      "Intersex",
      "Non-binary/third gender",
      "Transgender female",
      "Transgender male",
      "Other/not listed",
      "I prefer not to self-describe",
      "I prefer not to self-identify",
    ],
    disability: [
      "Yes, I have (or have previously had) a visible disability",
      "Yes, I have (or have previously had) an invisible disability",
      "No, I don't have a disability",
      "I'd prefer not to say",
    ],
    interests: [
      "Broadcast",
      "Radio",
      "TV News",
      "TV Programming",
      "Documentary",
      "Print",
      "Online",
      "Social Media",
      "Publishing",
      "PR",
      "Other",
    ],
    workingArea: [
      "Broadcast",
      "Radio",
      "TV News",
      "TV Programming",
      "Documentary",
      "Print",
      "Online",
      "Social Media",
      "Publishing",
      "PR",
      "Other",
    ],
    accommodationChecklist: [
      "Lock on the bathroom door",
      "Lock on the bedroom door",
      "Spare key for intern",
      "You’ll be there to welcome them on their first day",
      "WiFi code made available",
      "Bed linen including towel",
      "Space provided in fridge and cupboard for intern’s food",
      "You can provide info for someone they can contact if you’re not available (neighbour/emergency contact/partner etc.) - this will be done once the booking is confirmed",
      "None of these",
    ],
    degreeLevel: [
      "GCSEs",
      "A levels or equivalent (International Baccalaureate diploma, HNC, NVQ Level",
      "4-5 HNC, HND, RSA Higher Diploma, BTEX Higher Level, non-UK qualification equivalent)",
      "Undergraduate degree or equivalent",
      "Professional qualification (e.g. teaching, nursing, accountancy",
      "Master's degree",
      "PhD/Doctoral degree",
      "I'd prefer not to say",
    ], // waiting for PO to send over
    earningOfParents: [
      "Modern professional occupations such as (teacher, nurse, physiotherapist, social worker, musician, police officer (sergeant or above), software designer)",
      "Clerical and intermediate occupations (such as secretary, personal assistant, clerical worker, call centre agent, nursery nurse)",
      "Senior managers or administrators usually responsible for planning, organising and co-ordinator work, and for finance (such as finance manager, chief executive)",
      "Technical and craft occupations (such as motor mechanic, plumber, printer, electrician, gardener, train driver)",
      "Semi-routine manual and service occupations (such as postal worker, machine operative, security guard, caretaker, farm worker, catering assistant, sales assistant)",
      "Routine manual and service occupations (such as lorry driver, cleaner, porter, packer, labourer, waiter/waitress, bar staff)",
      "Middle or junior managers (such as office manager, retail manager, bank manager, restaurant manager, warehouse manager)",
      "Traditional professional occupations (such as accountant, solicitor, medical practitioner, scientist, civil / mechanical engineer)",
      "Unemployed",
      "I'd prefer not to say",
    ],
  },
};
