const API_PREFIX = "/api";

const LOGIN_URL = "/user/login"; // to use on the server
const API_LOGIN_URL = `${API_PREFIX}${LOGIN_URL}`; // to use on the client

const SIGNUP_URL = "/user/signup";
const API_SIGNUP_URL = `${API_PREFIX}${SIGNUP_URL}`;

const CHECK_REFERRAL_URL = "/user/check-referral";
const API_CHECK_REFERRAL_URL = `${API_PREFIX}${CHECK_REFERRAL_URL}`;

const USER_URL = "/user/check-user";
const API_USER_URL = `${API_PREFIX}${USER_URL}`;

const GET_ORGS_URL = "/user/get-all-orgs";
const API_GET_ORGS_URL = `${API_PREFIX}${GET_ORGS_URL}`;

const HOST_PROFILE_URL = "/host/";
const API_HOST_PROFILE_URL = `${API_PREFIX}${HOST_PROFILE_URL}`;

const HOST_COMPLETE_PROFILE = "/hosts/complete-profile";
const API_HOST_COMPLETE_PROFILE = `${API_PREFIX}${HOST_COMPLETE_PROFILE}`;

const SEARCH_PROFILES_URL = "/search-profiles";
const API_SEARCH_PROFILES_URL = `${API_PREFIX}${SEARCH_PROFILES_URL}`;

module.exports = {
  // CLIENT
  API_LOGIN_URL,
  API_SIGNUP_URL,
  API_USER_URL,
  API_CHECK_REFERRAL_URL,
  API_GET_ORGS_URL,
  API_HOST_COMPLETE_PROFILE,
  API_HOST_PROFILE_URL,
  API_SEARCH_PROFILES_URL,
  // SERVER
  LOGIN_URL,
  SIGNUP_URL,
  USER_URL,
  CHECK_REFERRAL_URL,
  GET_ORGS_URL,
  HOST_COMPLETE_PROFILE,
  HOST_PROFILE_URL,
  SEARCH_PROFILES_URL
};
