export default {
  sexualOrientation: [
    "Male to Female (MtF)",
    "Female to Male (FtM)",
    "Binary",
    "Non-Binary",
    "Genderfluid",
    "Agender",
    "Bigender",
    "Polygender",
    "Neutrois",
    "Gender Apathetic",
    "Androgyne",
    "Intergender",
    "Demigender",
    "Greygender",
    "Aporagender",
    "Maverique",
    "Novigender",
    "Designated gender",
    "AFAB",
    "AMAB",
    "Gender roles",
    "Gender Presentation",
    "Transitioning",
    "Intersex",
    "Dyadic",
    "Trans Woman",
    "Trans Man",
    "Trans Feminine",
    "Trans Masculine",
    "Social Dysphoria",
    "Body Dysphoria",
    "Butch",
    "Femme (Fem)",
    "Binarism",
  ],
  ethnicity: [
    "White or White British",
    "Gypsy/Traveller/Irish Travelle",
    "Asian or Asian British: Indian",
    "Asian or Asian British: Pakistani",
    "Asian or Asian British: Bangladeshi",
    "Asian or Asian British: Chinese",
    "Asian or Asian British: Other Asian",
    "Asian or Asian British",
    "Mixed or Multiple",
    "Other Ethnic Group",
  ],
  parentsWorkInPress: ["Mom", "Dad", "Both"],
  gender: ["male", "female", "other", "prefer not to say"],
  disability: [], // waiting for PO to send over
  interests: ["asd"], // waiting for PO to send over
  degreeLevel: [], // waiting for PO to send over
  earningOfParents: [], // waiting for PO to send over
  workingArea: [],
  accommodationChecklist: [
    "Lock on the bathroom door",
    "Lock on the bedroom door",
    "Spare key for intern",
    "You’ll be there to welcome them on their first day",
    "WiFi code made available",
    "Bed linen including towel",
    "Space provided in fridge and cupboard for intern’s food",
    "You can provide info for someone they can contact if you’re not available (neighbour/emergency contact/partner etc.) - this will be done once the booking is confirmed",
    "None of these",
  ],
};
