// this schema stores all the unique codes generated by an organisation for their interns

const mongoose = require("mongoose");

const { Schema, model } = mongoose;

const orgCodesSchema = new Schema({
  code: {
    type: String,
    required: true,
  },
  organisation: {
    type: Schema.Types.ObjectId,
    ref: "organisations",
  },
}, {
  timestamps: true,
});

const OrgCodes = model("orgCodes", orgCodesSchema);

module.exports = OrgCodes;
